import { readdir, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";

export interface GenerateOptions {
  directory: string;
  outputDirectory?: string;
  packageName?: string;
}

/** Generate static imports. Vite, Bun and TS see the same module graph. */
export async function generateScenarios(options: GenerateOptions) {
  const root = resolve(options.directory);
  const out = resolve(options.outputDirectory ?? root);
  const files: string[] = [];
  async function walk(dir: string) {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
      const file = resolve(dir, entry.name);
      if (entry.isDirectory()) await walk(file);
      else if (/\.(route|scenario)\.ts$/.test(entry.name)) files.push(file);
    }
  }
  await walk(root);
  files.sort();
  const specifier = (file: string) => {
    const rel = relative(out, file).split(sep).join("/");
    return JSON.stringify(rel.startsWith(".") ? rel : "./" + rel);
  };
  const routes = files.filter((f) => f.endsWith(".route.ts"));
  const scenarios = files.filter((f) => f.endsWith(".scenario.ts"));
  const imports = (items: string[]) => items.map((f, i) => "import item" + i + " from " + specifier(f) + ";").join("\n");
  const keys = routes.map((f) => relative(root, f).split(sep).join("/").replace(/\.route\.ts$/, ""));
  const header = "// Generated by scenario-sim. Do not edit.\n";
  const outputs = {
    "routes.gen.ts": header + "import { defineRoutes, createScenarioBuilder } from " + JSON.stringify(options.packageName ?? "@omniaura/scenario-sim") + ";\n" + imports(routes) + "\nexport const routes = defineRoutes({\n" + keys.map((key, i) => "  " + JSON.stringify(key) + ": item" + i + ",").join("\n") + "\n});\nexport const scenario = createScenarioBuilder(routes);\n",
    "scenarios.gen.ts": header + imports(scenarios) + "\nexport const scenarios = [" + scenarios.map((_, i) => "item" + i).join(", ") + "];\nexport default scenarios;\n",
  };
  for (const [name, content] of Object.entries(outputs)) {
    const file = resolve(out, name);
    await mkdir(dirname(file), { recursive: true });
    const previous = await readFile(file, "utf8").catch(() => null);
    if (previous !== content) await writeFile(file, content);
  }
  return { routes: routes.length, scenarios: scenarios.length, outputDirectory: out };
}
